-- =====================================================================
-- Base de datos completa de la aplicacion (modulos que faltaban)
-- =====================================================================
--
-- Este archivo crea el esquema "webadministrativa" con las tablas de los
-- modulos que todavia no tenian un lugar donde guardarse:
--
--    1. usuarios            (datos sensibles)
--    2. clientes            (datos sensibles, con perfil de salud y actividad)
--    3. membresias          (estado y vigencia de la membresia del cliente)
--    4. clases              (catalogo de clases)
--    5. horarios            (agenda de cada clase)
--    6. reservaciones       (apartado de lugares por clase)
--    7. productos           (catalogo de productos del negocio)
--    8. movimientos         (entradas, salidas y mermas de inventario)
--    9. ventas              (encabezado de cada venta)
--   10. venta_detalle       (productos que se cobraron en cada venta)
--
-- Por que un esquema propio:
-- la base de datos se comparte con las demas aplicaciones del equipo, asi
-- que cada aplicacion guarda sus tablas dentro de su propio esquema en
-- lugar de crearlas sueltas en "public". Los esquemas que ya existian son:
--
--   webpontoventa -> productos, ventas, venta_detalle, mermas, cortes de caja
--                    (archivo backend/db/schema.sql)
--   webcobro      -> clientes, clases, reservas, pagos, empleados, asistencias
--                    (archivo backend-cobro/db/schema.sql)
--
-- Reparto entre PostgreSQL y MongoDB:
--   PostgreSQL guarda los datos sensibles y los que necesitan relacionarse
--   entre si (usuarios, clientes, membresias, reservaciones, ventas y su
--   detalle), porque aqui puedo usar llaves foraneas, restricciones y
--   transacciones.
--
--   MongoDB queda para los datos menos estrictos, que son los catalogos y
--   los movimientos (clases, horarios, productos y movimientos), porque su
--   estructura cambia seguido y no necesita relaciones estrictas. Esa
--   estructura esta descrita en el archivo estructura-mongodb.md y todavia
--   no se implementa.
--
-- El archivo se puede ejecutar las veces que haga falta porque todas las
-- instrucciones usan IF NOT EXISTS, y no borro nada para no perder datos.
--
-- Para ejecutarlo puedo usar la herramienta Query Tool de pgAdmin, o el
-- comando (desde PowerShell, que no tiene el simbolo "<"):
--   Get-Content .\backend\db\esquema-completo.sql -Raw | docker exec -i punto-venta-postgres psql -U admin -d punto_venta -v ON_ERROR_STOP=1
-- =====================================================================

-- Creo el esquema de esta aplicacion dentro de la base de datos compartida.
CREATE SCHEMA IF NOT EXISTS webadministrativa;

-- Me coloco dentro del esquema recien creado para no tener que escribir
-- "webadministrativa." antes del nombre de cada tabla.
SET search_path TO webadministrativa;

-- =====================================================================
-- 1. Usuarios de la plataforma
-- =====================================================================
-- Aqui van las personas que entran al sistema con un usuario y una
-- contrasena (administrador, entrenador y recepcion). El cliente no usa
-- esta tabla porque solo entra desde la aplicacion movil, y su informacion
-- se guarda en la tabla clientes.

CREATE TABLE IF NOT EXISTS usuarios (
    -- Identificador interno. Uso GENERATED BY DEFAULT para poder guardar
    -- tambien identificadores fijos cuando cargue datos de ejemplo.
    id                  INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre              VARCHAR(80)  NOT NULL,
    apellidos           VARCHAR(80)  NOT NULL,

    -- Correo con el que inicia sesion. Es unico porque no puede haber dos
    -- usuarios con el mismo correo.
    correo              VARCHAR(150) NOT NULL UNIQUE,

    -- Guardo la contrasena cifrada, nunca en texto plano.
    contrasena_hash     VARCHAR(255) NOT NULL,

    telefono            VARCHAR(30)  NOT NULL DEFAULT '',

    -- Codigo que se le entrega al usuario para el reloj checador. Es unico
    -- para que el sistema identifique a una sola persona con ese codigo.
    codigo_acceso       VARCHAR(20)  NOT NULL UNIQUE,

    -- Tipo de usuario. Solo permito estos tres porque el cliente no entra
    -- a esta plataforma.
    rol                 VARCHAR(15)  NOT NULL
                        CHECK (rol IN ('administrador', 'entrenador', 'recepcion')),

    -- Un usuario inactivo ya no puede entrar al sistema, pero no se borra
    -- para no perder su historial.
    estatus             VARCHAR(10)  NOT NULL DEFAULT 'activo'
                        CHECK (estatus IN ('activo', 'inactivo')),

    avatar              VARCHAR(255) DEFAULT NULL,

    -- Fecha de alta y fecha de la ultima modificacion del registro.
    fecha_creacion      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- =====================================================================
-- 2. Clientes
-- =====================================================================
-- Ademas de sus datos personales, guardo su perfil de salud y su perfil de
-- actividad, porque son los que captura desde la aplicacion movil.

CREATE TABLE IF NOT EXISTS clientes (
    id                   INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre               VARCHAR(80)   NOT NULL,
    apellidos            VARCHAR(80)   NOT NULL,

    -- Correo de acceso a la aplicacion movil. Es unico por el mismo motivo
    -- que en los usuarios.
    correo               VARCHAR(150)  NOT NULL UNIQUE,
    contrasena_hash      VARCHAR(255)  NOT NULL,

    telefono             VARCHAR(30)   NOT NULL DEFAULT '',
    codigo_acceso        VARCHAR(20)   NOT NULL UNIQUE,
    estatus              VARCHAR(10)   NOT NULL DEFAULT 'activo'
                         CHECK (estatus IN ('activo', 'inactivo')),
    avatar               VARCHAR(255)  DEFAULT NULL,

    fecha_nacimiento     DATE          DEFAULT NULL,
    direccion            VARCHAR(200)  NOT NULL DEFAULT '',
    fecha_registro       DATE          NOT NULL DEFAULT CURRENT_DATE,

    -- ---- Perfil de salud ----
    -- Uso NUMERIC para el peso y un entero para la altura en centimetros.
    peso                 NUMERIC(5,2)  CHECK (peso IS NULL OR peso > 0),
    altura               INTEGER       CHECK (altura IS NULL OR altura > 0),
    tipo_sangre          VARCHAR(5)    NOT NULL DEFAULT '',

    -- Las alergias, enfermedades y lesiones son listas, por eso las guardo
    -- como arreglos de texto.
    alergias             TEXT[]        NOT NULL DEFAULT '{}',
    enfermedades         TEXT[]        NOT NULL DEFAULT '{}',
    lesiones             TEXT[]        NOT NULL DEFAULT '{}',
    observaciones_salud  VARCHAR(300)  NOT NULL DEFAULT '',

    -- ---- Perfil de actividad y hobbies ----
    nivel_actividad      VARCHAR(15)   NOT NULL DEFAULT 'sedentario'
                         CHECK (nivel_actividad IN ('sedentario', 'ligero', 'moderado', 'activo', 'muy activo')),
    objetivo             VARCHAR(200)  NOT NULL DEFAULT '',
    frecuencia_ejercicio VARCHAR(80)   NOT NULL DEFAULT '',
    hobbies              TEXT[]        NOT NULL DEFAULT '{}',

    fecha_creacion       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- =====================================================================
-- 3. Membresias
-- =====================================================================
-- La membresia va en su propia tabla y no dentro de clientes, porque un
-- cliente puede renovar varias veces a lo largo del tiempo y necesito
-- conservar el historial de cada periodo. La membresia que muestra la
-- pantalla es la que todavia esta vigente.

CREATE TABLE IF NOT EXISTS membresias (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Si se borra un cliente se borran sus membresias, porque no tienen
    -- sentido sin el.
    cliente_id    INTEGER       NOT NULL REFERENCES clientes (id) ON DELETE CASCADE,

    tipo          VARCHAR(12)   NOT NULL
                  CHECK (tipo IN ('mensual', 'trimestral', 'semestral', 'anual')),

    fecha_inicio  DATE          NOT NULL,
    fecha_fin     DATE          NOT NULL,

    precio        NUMERIC(10,2) NOT NULL CHECK (precio >= 0),

    estatus       VARCHAR(10)   NOT NULL DEFAULT 'activo'
                  CHECK (estatus IN ('activo', 'inactivo')),

    creado_en     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- La fecha de fin no puede ser anterior a la de inicio.
    CHECK (fecha_fin >= fecha_inicio)
);

-- Indice para encontrar rapido la membresia vigente de un cliente.
CREATE INDEX IF NOT EXISTS membresias_cliente_idx
    ON membresias (cliente_id, fecha_fin DESC);

-- =====================================================================
-- 4. Clases
-- =====================================================================
-- Es el catalogo de clases que se pueden impartir: su nombre, su capacidad
-- y el entrenador asignado.

CREATE TABLE IF NOT EXISTS clases (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre        VARCHAR(80)  NOT NULL,
    descripcion   VARCHAR(250) NOT NULL DEFAULT '',

    -- Cuantos clientes caben en la clase.
    capacidad     INTEGER      NOT NULL CHECK (capacidad > 0),

    -- Color con el que se pinta la clase en el calendario de la pantalla.
    color         VARCHAR(20)  NOT NULL DEFAULT '#10b981',

    -- Entrenador asignado. Si el usuario se borra, la clase se queda sin
    -- entrenador en lugar de desaparecer, por eso SET NULL.
    entrenador_id INTEGER      REFERENCES usuarios (id) ON DELETE SET NULL,

    estatus       VARCHAR(10)  NOT NULL DEFAULT 'activo'
                  CHECK (estatus IN ('activo', 'inactivo')),

    creado_en     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- =====================================================================
-- 5. Horarios
-- =====================================================================
-- Cada renglon es una clase con su fecha, su hora y su entrenador, que es
-- lo que veo en la pantalla de Horarios.

CREATE TABLE IF NOT EXISTS horarios (
    id                   INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Si se borra la clase, sus horarios ya no sirven, por eso CASCADE.
    clase_id             INTEGER     NOT NULL REFERENCES clases (id) ON DELETE CASCADE,

    -- Al entrenador no lo puedo borrar mientras tenga horarios asignados,
    -- por eso RESTRICT.
    entrenador_id        INTEGER     NOT NULL REFERENCES usuarios (id) ON DELETE RESTRICT,

    fecha                DATE        NOT NULL,
    hora_inicio          TIME        NOT NULL,
    hora_fin             TIME        NOT NULL,

    capacidad_total      INTEGER     NOT NULL CHECK (capacidad_total > 0),

    -- Lugares que todavia quedan libres; se descuentan al reservar.
    capacidad_disponible INTEGER     NOT NULL CHECK (capacidad_disponible >= 0),

    salon                VARCHAR(40) NOT NULL,

    estatus              VARCHAR(10) NOT NULL DEFAULT 'activo'
                         CHECK (estatus IN ('activo', 'inactivo')),

    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- La clase no puede terminar antes de empezar.
    CHECK (hora_fin > hora_inicio),

    -- Los lugares disponibles nunca pueden ser mas que el total.
    CHECK (capacidad_disponible <= capacidad_total)
);

-- La misma clase no se puede repetir en la misma fecha y hora.
CREATE UNIQUE INDEX IF NOT EXISTS horarios_clase_fecha_hora_idx
    ON horarios (clase_id, fecha, hora_inicio);

-- El mismo entrenador tampoco puede estar en dos clases a la misma hora.
CREATE UNIQUE INDEX IF NOT EXISTS horarios_entrenador_fecha_hora_idx
    ON horarios (entrenador_id, fecha, hora_inicio);

-- =====================================================================
-- 6. Reservaciones
-- =====================================================================
-- Aparto un lugar de un horario para un cliente. No guardo otra vez el
-- nombre de la clase ni el del entrenador porque esos datos ya viven en las
-- tablas clases, horarios y usuarios: si los copiara aqui tendria que
-- actualizarlos en dos lugares y se podrian contradecir.

CREATE TABLE IF NOT EXISTS reservaciones (
    id                    INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Al cliente no lo puedo borrar mientras tenga reservaciones, por eso
    -- RESTRICT.
    cliente_id            INTEGER     NOT NULL REFERENCES clientes (id) ON DELETE RESTRICT,

    -- Si se borra el horario, sus reservaciones ya no sirven, por eso CASCADE.
    horario_id            INTEGER     NOT NULL REFERENCES horarios (id) ON DELETE CASCADE,

    -- Fecha en la que se hizo el apartado (no es la fecha de la clase, esa
    -- esta en el horario).
    fecha_reservacion     DATE        NOT NULL DEFAULT CURRENT_DATE,

    estatus               VARCHAR(12) NOT NULL DEFAULT 'pendiente'
                          CHECK (estatus IN ('pendiente', 'confirmada', 'cancelada')),

    -- Se marca cuando recepcion confirma que el cliente llego a la clase.
    asistencia_confirmada BOOLEAN     NOT NULL DEFAULT FALSE,

    creado_en             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Un cliente no puede apartar dos veces el mismo horario.
CREATE UNIQUE INDEX IF NOT EXISTS reservaciones_cliente_horario_idx
    ON reservaciones (cliente_id, horario_id);

-- Indice para contar los lugares ocupados de un horario.
CREATE INDEX IF NOT EXISTS reservaciones_horario_idx
    ON reservaciones (horario_id, estatus);

-- =====================================================================
-- 7. Productos
-- =====================================================================
-- Catalogo de lo que vende el negocio. El Punto de Venta maneja ademas el
-- costo y la existencia minima en su propio esquema (webpontoventa), aqui
-- solo guardo los campos que muestra la pantalla de Inventario.

CREATE TABLE IF NOT EXISTS productos (
    id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre         VARCHAR(120)  NOT NULL,
    descripcion    VARCHAR(250)  NOT NULL DEFAULT '',

    -- Precio que paga el cliente. Uso NUMERIC en lugar de FLOAT para no
    -- perder centavos por el redondeo.
    precio         NUMERIC(10,2) NOT NULL CHECK (precio >= 0),

    -- Existencia actual. El CHECK evita existencias negativas.
    stock          INTEGER       NOT NULL DEFAULT 0 CHECK (stock >= 0),

    categoria      VARCHAR(60)   NOT NULL,

    estatus        VARCHAR(10)   NOT NULL DEFAULT 'activo'
                   CHECK (estatus IN ('activo', 'inactivo')),

    creado_en      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Indice para los filtros por categoria del catalogo.
CREATE INDEX IF NOT EXISTS productos_categoria_idx
    ON productos (categoria);

-- =====================================================================
-- 8. Movimientos de inventario
-- =====================================================================
-- Bitacora de lo que entra y sale del inventario. Cada renglon explica por
-- que cambio la existencia de un producto, y con esto el modulo de Reportes
-- puede calcular las perdidas por mermas.

CREATE TABLE IF NOT EXISTS movimientos (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Si el producto todavia tiene movimientos no lo puedo borrar, por eso
    -- RESTRICT: prefiero desactivarlo y no perder el historial.
    producto_id INTEGER      NOT NULL REFERENCES productos (id) ON DELETE RESTRICT,

    tipo        VARCHAR(10)  NOT NULL
                CHECK (tipo IN ('entrada', 'salida', 'merma')),

    -- Siempre guardo la cantidad en positivo y el tipo me dice si sumo o
    -- resto, asi no hay cantidades con signos encontrados.
    cantidad    INTEGER      NOT NULL CHECK (cantidad > 0),

    motivo      VARCHAR(200) NOT NULL DEFAULT '',

    -- Quien registro el movimiento. Si el usuario se borra, el movimiento se
    -- conserva pero sin responsable, por eso SET NULL.
    usuario_id  INTEGER      REFERENCES usuarios (id) ON DELETE SET NULL,

    creado_en   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Indice para ver la ultima actividad de un producto.
CREATE INDEX IF NOT EXISTS movimientos_producto_idx
    ON movimientos (producto_id, creado_en DESC);

-- =====================================================================
-- 9. Ventas
-- =====================================================================
-- Encabezado de cada venta cobrada. Los articulos van en venta_detalle.

CREATE TABLE IF NOT EXISTS ventas (
    id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Folio visible en el ticket. Es unico para no repetir una venta.
    folio            VARCHAR(20)   NOT NULL UNIQUE,

    -- Cliente que compro. Acepto NULL porque una venta tambien puede ser a
    -- publico general; si el cliente se borra, la venta se conserva.
    cliente_id       INTEGER       REFERENCES clientes (id) ON DELETE SET NULL,

    -- Quien cobro la venta (recepcion o administrador). No lo puedo borrar
    -- mientras tenga ventas registradas, por eso RESTRICT.
    recepcionista_id INTEGER       NOT NULL REFERENCES usuarios (id) ON DELETE RESTRICT,

    -- Fecha y hora del cobro en un solo instante, en lugar de separar fecha
    -- y hora: la pantalla se encarga de mostrarlo en formato es-MX.
    fecha            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- Suma de los articulos antes del descuento.
    subtotal         NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),

    -- Descuento aplicado a la venta.
    descuento        NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),

    -- Total cobrado al cliente.
    total            NUMERIC(10,2) NOT NULL CHECK (total >= 0),

    forma_pago       VARCHAR(15)   NOT NULL
                     CHECK (forma_pago IN ('efectivo', 'tarjeta', 'transferencia')),

    -- Una venta cancelada se conserva para el historial pero ya no cuenta.
    estatus          VARCHAR(10)   NOT NULL DEFAULT 'pagada'
                     CHECK (estatus IN ('pagada', 'cancelada'))
);

-- Indices para los reportes de ventas por dia y por forma de pago.
CREATE INDEX IF NOT EXISTS ventas_fecha_idx
    ON ventas (fecha DESC);
CREATE INDEX IF NOT EXISTS ventas_forma_pago_idx
    ON ventas (forma_pago);

-- =====================================================================
-- 10. Detalle de ventas
-- =====================================================================
-- Cada renglon es un producto que se cobro dentro de una venta.

CREATE TABLE IF NOT EXISTS venta_detalle (
    id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Si se borra la venta, su detalle ya no sirve, por eso CASCADE.
    venta_id        INTEGER       NOT NULL REFERENCES ventas (id) ON DELETE CASCADE,

    -- El producto puede borrarse del catalogo, pero el renglon de la venta se
    -- conserva; por eso acepto NULL y ademas guardo el nombre que tenia.
    producto_id     INTEGER       REFERENCES productos (id) ON DELETE SET NULL,

    -- Nombre que tenia el producto en el momento de la venta, para que el
    -- ticket siga siendo entendible aunque despues cambie en el catalogo.
    nombre_producto VARCHAR(120)  NOT NULL,

    cantidad        INTEGER       NOT NULL CHECK (cantidad > 0),

    -- Precio al que se cobro, que puede ser distinto al precio actual.
    precio_unitario NUMERIC(10,2) NOT NULL CHECK (precio_unitario >= 0),

    -- Resultado de cantidad por precio unitario.
    importe         NUMERIC(10,2) NOT NULL CHECK (importe >= 0)
);

-- Indice para armar el ticket y para los reportes por producto.
CREATE INDEX IF NOT EXISTS venta_detalle_venta_idx
    ON venta_detalle (venta_id);
CREATE INDEX IF NOT EXISTS venta_detalle_producto_idx
    ON venta_detalle (producto_id);

-- =====================================================================
-- Resumen de este archivo
-- =====================================================================
-- Modulo               Tabla             Guarda
-- usuarios             usuarios          Cuentas de la plataforma
-- clientes             clientes          Datos personales, salud y actividad
-- clientes             membresias        Periodos de la membresia
-- clases               clases            Catalogo de clases
-- horarios             horarios          Agenda de cada clase
-- reservaciones        reservaciones     Lugares apartados por cliente
-- productos            productos         Catalogo de productos
-- movimientos          movimientos       Entradas, salidas y mermas
-- ventas               ventas            Encabezado de la venta
-- ventas               venta_detalle     Productos cobrados
--
-- Datos que se quedan en MongoDB (todavia no implementado, la estructura
-- esta en el archivo estructura-mongodb.md):
--     clases, horarios, productos y movimientos, por ser catalogos y
--     movimientos que cambian seguido y no necesitan relaciones estrictas.
--
-- Modulos que pertenecen a otras aplicaciones y por eso no van aqui:
--     mermas y cortes de caja  -> esquema webpontoventa
--     pagos y asistencias      -> esquema webcobro