-- =====================================================================
-- Esquema de la base de datos del sistema web de Punto de Venta
-- =====================================================================
--
-- Este archivo crea el esquema "webpontoventa" y las cinco tablas con las
-- que voy a guardar la informacion del sistema: los productos, las ventas,
-- el detalle de cada venta, las mermas y los cortes de caja.
--
-- Uso un esquema propio porque la base de datos es compartida con las demas
-- aplicaciones del equipo, asi que cada aplicacion guarda sus tablas dentro
-- de su propio esquema en lugar de crearlas sueltas en "public".
--
-- El archivo se puede ejecutar las veces que haga falta porque todas las
-- instrucciones usan IF NOT EXISTS, y no borro nada para no perder datos.
--
-- Para ejecutarlo puedo usar la herramienta Query Tool de pgAdmin, o el
-- comando (desde PowerShell, que no tiene el simbolo "<"):
--   Get-Content .\backend\db\schema.sql -Raw | docker exec -i punto-venta-postgres psql -U admin -d punto_venta -v ON_ERROR_STOP=1
-- =====================================================================

-- Creo el esquema de esta aplicacion dentro de la base de datos compartida.
CREATE SCHEMA IF NOT EXISTS webpontoventa;

-- Me coloco dentro del esquema recien creado para no tener que escribir
-- "webpontoventa." antes del nombre de cada tabla.
SET search_path TO webpontoventa;

-- =====================================================================
-- 1. Productos
-- =====================================================================

-- Guardo el catalogo completo con precios, costos, existencias y estado de
-- cada producto, que es la base del modulo de Inventario y del Punto de Venta.
CREATE TABLE IF NOT EXISTS products (
    -- Identificador interno. Uso GENERATED BY DEFAULT en lugar de GENERATED
    -- ALWAYS para que la carga inicial pueda guardar los mismos ids que ya
    -- usaba el frontend.
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Codigo o SKU con el que el negocio localiza el producto.
    code          VARCHAR(20)   NOT NULL UNIQUE,

    -- Nombre que se muestra en las tarjetas del Punto de Venta y en el ticket.
    name          VARCHAR(120)  NOT NULL,

    -- Descripcion breve que veo en el detalle del producto.
    description   VARCHAR(250)  NOT NULL DEFAULT '',

    -- Categoria que alimenta los filtros de Inventario y de Venta.
    category      VARCHAR(60)   NOT NULL,

    -- Precio que paga el cliente. Uso NUMERIC en lugar de FLOAT para que los
    -- importes no pierdan centavos por el redondeo.
    price         NUMERIC(10,2) NOT NULL CHECK (price >= 0),

    -- Costo estimado del producto, lo necesito para calcular la perdida por
    -- mermas en el modulo de Reportes.
    cost          NUMERIC(10,2) NOT NULL CHECK (cost >= 0),

    -- Existencia actual. Con este CHECK evito existencias negativas.
    stock         INTEGER       NOT NULL DEFAULT 0 CHECK (stock >= 0),

    -- Existencia minima a partir de la cual marco el producto con pocas
    -- existencias en la pantalla de Venta.
    minimum_stock INTEGER       NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0),

    -- Estado administrativo: un producto inactivo sigue en el inventario pero
    -- ya no se puede vender.
    status        VARCHAR(10)   NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'inactive')),

    -- Nombre del icono y color de la tarjeta, para no perder el diseno actual.
    icon          VARCHAR(40)   NOT NULL DEFAULT 'inventory_2',
    bg_color      VARCHAR(20)   NOT NULL DEFAULT '#F3F4F6',

    -- Fecha de alta y fecha de la ultima modificacion del registro.
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);


-- =====================================================================
-- 2. Ventas
-- =====================================================================

-- Guardo el encabezado de cada venta cobrada: el folio, el importe y la
-- forma de pago. Los articulos de la venta van en la tabla sale_items.
CREATE TABLE IF NOT EXISTS sales (
    -- Identificador interno de la venta.
    id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Folio visible en el ticket. Es unico para no repetir una venta.
    folio          VARCHAR(20)   NOT NULL UNIQUE,

    -- Fecha y hora del cobro. Guardo un solo instante con zona horaria en
    -- lugar de separar "fecha" y "hora": la pantalla se encarga de mostrarlo
    -- en formato es-MX y asi no hay dos valores que se puedan contradecir.
    sold_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- Suma de los articulos antes del descuento.
    subtotal       NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),

    -- Descuento aplicado a la venta.
    discount       NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),

    -- Total cobrado al cliente.
    total          NUMERIC(10,2) NOT NULL CHECK (total >= 0),

    -- Forma de pago. Solo permito los tres valores que ya maneja el sistema.
    payment_method VARCHAR(15)   NOT NULL
                   CHECK (payment_method IN ('efectivo', 'tarjeta', 'transferencia')),

    -- Efectivo que entrego el cliente y cambio devuelto. Solo aplican para
    -- pagos en efectivo, por eso acepto NULL en las otras formas de pago.
    cash_received  NUMERIC(10,2) DEFAULT NULL
                   CHECK (cash_received IS NULL OR cash_received >= 0),
    change_amount  NUMERIC(10,2) DEFAULT NULL
                   CHECK (change_amount IS NULL OR change_amount >= 0),

    -- Referencia de la transferencia, cuando la venta se cobra asi.
    transfer_ref   VARCHAR(60)   DEFAULT NULL,

    -- Estado de la venta. Por ahora todas se guardan como completadas y dejo
    -- el campo preparado para cuando agreguemos la cancelacion de una venta.
    status         VARCHAR(10)   NOT NULL DEFAULT 'completed'
                   CHECK (status IN ('completed', 'cancelled'))
);

-- =====================================================================
-- 3. Detalle de las ventas
-- =====================================================================

-- Guardo una fila por cada articulo que se cobro en una venta.
CREATE TABLE IF NOT EXISTS sale_items (
    -- Identificador interno de la linea.
    id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Venta a la que pertenece la linea. Si alguna vez se borra la venta, sus
    -- lineas se borran con ella para no dejar registros sueltos.
    sale_id      INTEGER       NOT NULL
                 REFERENCES sales (id) ON DELETE CASCADE,

    -- Producto vendido. Lo dejo opcional porque el carrito actual todavia no
    -- envia el id del producto, cuando lo agregue va a quedar obligatorio. Si
    -- el producto se eliminara del catalogo, conservo la linea con NULL para
    -- no perder el historial de la venta.
    product_id   INTEGER       REFERENCES products (id) ON DELETE SET NULL,

    -- Copia del nombre y del precio al momento de la venta: asi el ticket y
    -- los reportes no cambian si despues edito el producto.
    product_name VARCHAR(120)  NOT NULL,
    unit_price   NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),

    -- Cantidad cobrada y su importe (cantidad por precio unitario).
    quantity     INTEGER       NOT NULL CHECK (quantity > 0),
    line_total   NUMERIC(10,2) NOT NULL CHECK (line_total >= 0)
);

-- =====================================================================
-- 4. Mermas
-- =====================================================================

-- Guardo cada perdida de inventario con su motivo, para poder descontarla de
-- la existencia y despues analizarla en el modulo de Reportes.
CREATE TABLE IF NOT EXISTS waste_records (
    -- Identificador interno del registro.
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Folio visible de la merma.
    folio         VARCHAR(20)   NOT NULL UNIQUE,

    -- Producto afectado. Con ON DELETE RESTRICT evito borrar un producto que
    -- ya tiene mermas registradas y perder el historial.
    product_id    INTEGER       NOT NULL
                  REFERENCES products (id) ON DELETE RESTRICT,

    -- Unidades perdidas. Debe ser al menos una.
    quantity      INTEGER       NOT NULL CHECK (quantity > 0),

    -- Motivo de la merma, solo acepto los motivos que maneja el formulario.
    reason        VARCHAR(20)   NOT NULL
                  CHECK (reason IN ('damaged', 'expired', 'broken',
                                    'internal-use', 'inventory-error',
                                    'lost', 'other')),

    -- Explicacion adicional que captura el usuario.
    observations  VARCHAR(300)  NOT NULL DEFAULT '',

    -- Costo del producto en el momento de la merma. Lo guardo aqui para que
    -- la perdida calculada no cambie si despues se actualiza el costo.
    unit_cost     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),

    -- Fecha y hora del registro.
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- Usuario que registro el movimiento. Todavia no hay inicio de sesion, asi
    -- que dejo el nombre del usuario actual como valor por defecto.
    registered_by VARCHAR(80)   NOT NULL DEFAULT 'Edgar Rodriguez'
);

-- =====================================================================
-- 5. Cortes de caja
-- =====================================================================

-- Guardo el cierre de cada turno con los totales por forma de pago, el fondo
-- inicial, el efectivo contado y la diferencia calculada.
CREATE TABLE IF NOT EXISTS cash_closings (
    -- Identificador interno del corte.
    id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Folio visible del corte.
    folio          VARCHAR(20)   NOT NULL UNIQUE,

    -- Fecha y hora en que se cerro el turno.
    closed_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- Cantidad de ventas que quedaron incluidas en el turno.
    sales_count    INTEGER       NOT NULL CHECK (sales_count >= 0),

    -- Importe total vendido en el turno.
    total_sales    NUMERIC(10,2) NOT NULL CHECK (total_sales >= 0),

    -- Importes separados por forma de pago.
    cash_sales     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (cash_sales >= 0),
    card_sales     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (card_sales >= 0),
    transfer_sales NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (transfer_sales >= 0),

    -- Dinero con el que inicio el turno.
    initial_fund   NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (initial_fund >= 0),

    -- Efectivo que debia existir en la caja (fondo mas ventas en efectivo).
    expected_cash  NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (expected_cash >= 0),

    -- Efectivo que el usuario conto al final del turno.
    counted_cash   NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (counted_cash >= 0),

    -- Diferencia entre lo contado y lo esperado. Aqui no pongo CHECK porque el
    -- resultado puede ser positivo (sobrante) o negativo (faltante).
    difference     NUMERIC(10,2) NOT NULL DEFAULT 0,

    -- Usuario que realizo el corte.
    registered_by  VARCHAR(80)   NOT NULL DEFAULT 'Edgar Rodriguez'
);

-- =====================================================================
-- 6. Indices para las consultas mas frecuentes
-- =====================================================================

-- Acelero las busquedas del modulo de Inventario por categoria y por estado.
CREATE INDEX IF NOT EXISTS idx_products_category ON products (category);
CREATE INDEX IF NOT EXISTS idx_products_status ON products (status);

-- Acelero los filtros de Reportes por rango de fechas y por forma de pago.
CREATE INDEX IF NOT EXISTS idx_sales_sold_at ON sales (sold_at);
CREATE INDEX IF NOT EXISTS idx_sales_payment_method ON sales (payment_method);

-- Indexo las llaves foraneas para que unir tablas no recorra tablas completas.
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON sale_items (product_id);
CREATE INDEX IF NOT EXISTS idx_waste_product_id ON waste_records (product_id);

-- Acelero los reportes de mermas por periodo.
CREATE INDEX IF NOT EXISTS idx_waste_created_at ON waste_records (created_at);

-- =====================================================================
-- 7. Descripcion de las tablas
-- =====================================================================

-- Estos comentarios quedan guardados en la base de datos y los puedo ver en
-- pgAdmin, por si alguien mas revisa el esquema o tengo que explicarlo.
COMMENT ON SCHEMA webpontoventa IS
    'Esquema con las tablas del sistema web de Punto de Venta';
COMMENT ON TABLE products IS
    'Catalogo de productos con precios, costos y existencias';
COMMENT ON TABLE sales IS
    'Encabezado de cada venta cobrada en el punto de venta';
COMMENT ON TABLE sale_items IS
    'Articulos que forman parte de cada venta';
COMMENT ON TABLE waste_records IS
    'Registro de mermas o perdidas de inventario';
COMMENT ON TABLE cash_closings IS
    'Cortes de caja realizados al cerrar cada turno';

-- =====================================================================
-- 8. Consultas de comprobacion (opcionales)
-- =====================================================================

-- Para verificar que las tablas se crearon puedo ejecutar:
--   SELECT table_name
--   FROM information_schema.tables
--   WHERE table_schema = 'webpontoventa'
--   ORDER BY table_name;

-- Para revisar como quedo una tabla (por ejemplo la de ventas):
--   SELECT column_name, data_type, is_nullable
--   FROM information_schema.columns
--   WHERE table_schema = 'webpontoventa' AND table_name = 'sales'
--   ORDER BY ordinal_position;
