-- =====================================================================
-- Esquema de base de datos de la aplicación web de cobro (front desk).
--
-- Reutiliza el mismo servidor PostgreSQL de la carpeta de punto de venta
-- siguiendo la convención del equipo: cada aplicación usa su propio
-- esquema (webcobro) dentro de la misma base, en vez de crear tablas
-- sueltas en public.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS webcobro;

-- Clientes que llegan a recepción.
CREATE TABLE IF NOT EXISTS webcobro.clientes (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    TEXT NOT NULL,
    membresia TEXT NOT NULL DEFAULT 'Básica',
    telefono  TEXT NOT NULL DEFAULT ''
);

-- Clases que se pueden cobrar en recepción.
CREATE TABLE IF NOT EXISTS webcobro.clases (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    precio NUMERIC(10, 2) NOT NULL CHECK (precio >= 0)
);

-- Reservaciones que se muestran en el tablero de recepción.
CREATE TABLE IF NOT EXISTS webcobro.reservas (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente TEXT NOT NULL,
    tipo    TEXT NOT NULL DEFAULT 'cliente'
        CHECK (tipo IN ('cliente', 'visitante')),
    clase   TEXT NOT NULL,
    hora    TEXT NOT NULL,
    estado  TEXT NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente', 'pagado', 'asistido', 'cancelado')),
    precio  NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (precio >= 0)
);

-- Si la tabla venía de la versión anterior, se agrega la columna tipo
-- (socio registrado o visitante) sin perder los registros guardados.
ALTER TABLE webcobro.reservas
    ADD COLUMN IF NOT EXISTS tipo TEXT NOT NULL DEFAULT 'cliente';

-- Un mismo horario no puede tener dos reservaciones de la misma clase.
CREATE UNIQUE INDEX IF NOT EXISTS reservas_clase_hora_idx
    ON webcobro.reservas (clase, hora)
    WHERE estado <> 'cancelado';

-- Pagos registrados desde el modal de cobro.
CREATE TABLE IF NOT EXISTS webcobro.pagos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id     INTEGER NOT NULL REFERENCES webcobro.clientes (id) ON DELETE RESTRICT,
    cliente_nombre TEXT NOT NULL,
    monto          NUMERIC(10, 2) NOT NULL CHECK (monto >= 0),
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS pagos_creado_en_idx ON webcobro.pagos (creado_en);

-- Empleados que usan el reloj checador (módulo de asistencia).
CREATE TABLE IF NOT EXISTS webcobro.empleados (
    codigo TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    rol    TEXT NOT NULL DEFAULT 'recepción'
);

-- Marcas de entrada y salida del reloj checador.
CREATE TABLE IF NOT EXISTS webcobro.asistencias (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo    TEXT NOT NULL REFERENCES webcobro.empleados (codigo) ON DELETE RESTRICT,
    nombre    TEXT NOT NULL,
    tipo      TEXT NOT NULL CHECK (tipo IN ('entrada', 'salida')),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS asistencias_codigo_idx ON webcobro.asistencias (codigo, creado_en DESC);
