import type { Product } from './types';

export const CATEGORIES = ['Todos', 'Bebidas', 'Suplementos', 'Botanas', 'Ropa', 'Accesorios'];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    code: "P-001",
    name: "Agua 1 L",
    description: "Agua natural purificada de 1 litro.",
    category: "Bebidas",
    price: 25,
    cost: 12,
    stock: 48,
    minimumStock: 10,
    status: "active",
    icon: "water_drop",
    bgColor: "#DBEAFE",
  },
  {
    id: 2,
    code: "P-002",
    name: "Bebida energética",
    description: "Bebida energizante con cafeína y vitaminas.",
    category: "Bebidas",
    price: 45,
    cost: 25,
    stock: 3,
    minimumStock: 5,
    status: "active",
    icon: "bolt",
    bgColor: "#FEF3C7",
  },
  {
    id: 3,
    code: "P-003",
    name: "Bebida isotónica",
    description: "Bebida con electrolitos para hidratación deportiva.",
    category: "Bebidas",
    price: 35,
    cost: 19,
    stock: 15,
    minimumStock: 6,
    status: "active",
    icon: "local_drink",
    bgColor: "#D1FAE5",
  },
  {
    id: 4,
    code: "P-004",
    name: "Proteína de suero",
    description: "Suplemento de proteína de suero de leche, 1 kg.",
    category: "Suplementos",
    price: 850,
    cost: 620,
    stock: 8,
    minimumStock: 3,
    status: "active",
    icon: "fitness_center",
    bgColor: "#EDE9FE",
  },
  {
    id: 5,
    code: "P-005",
    name: "Barra de proteína",
    description: "Barra energética con 20 g de proteína.",
    category: "Botanas",
    price: 40,
    cost: 21,
    stock: 2,
    minimumStock: 5,
    status: "active",
    icon: "nutrition",
    bgColor: "#FEE2E2",
  },
  {
    id: 6,
    code: "P-006",
    name: "Vaso mezclador",
    description: "Vaso mezclador de 600 ml con tapa de rosca.",
    category: "Accesorios",
    price: 120,
    cost: 65,
    stock: 0,
    minimumStock: 3,
    status: "active",
    icon: "water_bottle",
    bgColor: "#F3F4F6",
  },
  {
    id: 7,
    code: "P-007",
    name: "Toalla deportiva",
    description: "Toalla de microfibra de secado rápido.",
    category: "Accesorios",
    price: 150,
    cost: 80,
    stock: 6,
    minimumStock: 3,
    status: "active",
    icon: "dry_cleaning",
    bgColor: "#FDF4FF",
  },
  {
    id: 8,
    code: "P-008",
    name: "Playera deportiva",
    description: "Playera de entrenamiento con tecnología dry-fit.",
    category: "Ropa",
    price: 350,
    cost: 190,
    stock: 1,
    minimumStock: 2,
    status: "inactive",
    icon: "apparel",
    bgColor: "#ECFDF5",
  },
];